spring.application.name=ask-so
spring.main.banner-mode=off
spring.main.web-application-type=none
spring.ai.mcp.server.name=ask-so
spring.ai.mcp.server.version=0.1.0-SNAPSHOT
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.type=SYNC

rrb.base-uri=https://rrb.so.ch
rrb.connect-timeout=5s
rrb.request-timeout=20s
